# Generated by Django 5.0.3 on 2024-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=20, verbose_name='Document')),
                ('phone', models.CharField(max_length=15)),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('photo', models.CharField(max_length=512, verbose_name='URL')),
            ],
        ),
    ]
